export const REQUEST_TEST_DATA = 'REQUEST_TEST_DATA'
export const SHOW_TEST_DATA = 'SHOW_TEST_DATA'
export const FAILED_GET_TEST_DATA = 'FAILED_GET_TEST_DATA'
export const SUCCESS_TEST_DATA = 'SUCCESS_TEST_DATA'